db:
    image: mongo
    ports:
        - "27017"
app:
    image: node
    links:
        - db:mongo
    ports:
        - "80:3000"
    volumes:
        - .:/home/node
    working_dir: /home/node
    command: ./bin/www
